export const CLUE_THRESHOLD = 5; 

export const teamData: Record<string, number> = {
    "The Laggers": 17,
    "No Shit Sherlock!": 14,
    "Windows 5": 15,
    "The Baker Street Irregulars": 12,
    "Team GPS": 17,
    "The Brain Buffers": 9,
    "Team RIP": 6,
    "L": 17,
    "Ace of spades": 0,
    "Owl's Gaze": 9,
    "Baker Street Syndicate": 4,
    "The Valve Vigilantes": 9,
    "Holmes-less & Hopeless": 8,
    "যান্ত্রিক ঐক্য": 7,
    "TEAM ENTROPY": 7,
    "Mark 85": 8,
    "Quest Seekers": 8,
    "PentaCore": 6,
    "I am your treasure": 13,
    "Where is my treasure": 16,
    "X-MEN": 7,
    "Trouvaille": 9,
    "Sherlock Homies": 12,
    "Tantei": 9,
    "মুড়ির টিন": 9,
    "Sher-unlock Holmes": 9,
    "Pachmishali": 9,
    // Add all teams here...
};
