export const CLUE_THRESHOLD = 5; 

export const teamData: Record<string, number> = {
    "The Laggers": 0,
    "No Shit Sherlock!": 0,
    "Windows 5": 0,
    "The Baker Street Irregulars": 0,
    "Team GPS": 0,
    "The Brain Buffers": 0,
    "Team RIP": 0,
    "L": 0,
    "Ace of spades": 0,
    "Owl's Gaze ": 0,
    "Baker Street Syndicate": 0,
    "The Valve Vigilantes": 0,
    "Holmes-less & Hopeless": 0,
    "যান্ত্রিক ঐক্য": 0,
    "TEAM ENTROPY": 0,
    "Mark 85": 0,
    "Quest Seekers": 0,
    "PentaCore": 0,
    "I am your treasure": 0,
    "Where is my treasure": 0,
    "X-MEN": 0,
    "Trouvaille": 0,
    "Sherlock Homies": 0,
    "Tantei": 0,
    "মুড়ির টিন": 0,
    "Sher-unlock Holmes": 0,
    "Pachmishali": 0,
    // Add all teams here...
};
